Repository nimblehq/ic-rails-phong-bliss, pull requests merged in 2023-06, with the labels that each got.

#44 [#39] [Backend] As a user, I can receive a verification email after registration with email
  app/controllers/api/v1/confirmations_controller.rb
  app/models/user.rb
  config/application.yml
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  db/migrate/20230613043615_add_confirmable_to_devise.rb
  db/schema.rb
  spec/fabricators/user_fabricator.rb
Labels: type: feature, @0.2.0

#47 [#46] Fix: Heroku crashes because `simplecov`
  config/initializers/simplecov.rb
Labels: bug, @0.2.0

#54 [#14][#13] [Backend] [API] As a user, I can view my uploaded keywords with pagination
  app/controllers/api/v1/application_controller.rb
  app/controllers/api/v1/keywords_controller.rb
  config/initializers/pagy.rb
  spec/requests/api/v1/keywords_controller_spec.rb
Labels: type: feature, @0.3.0
